version: '2'
networks:
  bridge:
    driver: bridge
services:
    web:
      build:
        context: .
        dockerfile: flask.dockerfile
      ports:
        - 8100:8100
      command:
        - /bin/sh
        - -c
        - |
          cp local_set.tmp local_set.py
          python app.py 
      volumes:
        - .:/web-blog
      depends_on:
        - vue
        - mysql
      networks:
        - bridge

    vue:
      build: 
        context: .
        dockerfile: vue.dockerfile
      volumes:
        - .:/web-blog
      command: npm run build
      networks:
        - bridge

    init:
      build: 
        context: .
        dockerfile: flask.dockerfile
      depends_on:
        - mysql
      environment:
        - FLASK_APP=manager.py
      command:
        - /bin/sh
        - -c
        - |
          cp local_set.tmp local_set.py
          flask initdb
      networks:
        - bridge

    mysql:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_DATABASE: test
        MYSQL_USER: dev
        MYSQL_PASSWORD: test
      command:
        --character-set-server=utf8mb4
      ports:
        - 3306:3306
      restart: always
      volumes:
        - ./mysql_data:/var/lib/mysql
      networks:
        - bridge
